" built with love from
" - https://github.com/romainl/idiomatic-vimrc
" - https://linuxhint.com/vimrc_tutorial/

" enable pathogen (plugin manager)
execute pathogen#infect()

" Enabling filetype support provides filetype-specific indenting,
" syntax highlighting, omni-completion and other useful settings.
filetype plugin indent on
syntax on

" `matchit.vim` is built-in so let's enable it!
" Hit `%` on `if` to jump to `else`.
runtime macros/matchit.vim

" various QOL settings
set autoindent                 " Minimal automatic indenting for any filetype.
set backspace=indent,eol,start " Intuitive backspace behavior.
set hidden                     " Possibility to have more than one unsaved buffers.
set incsearch                  " Incremental search, hit `<CR>` to stop.
set hlsearch                   " ???
set ruler                      " Shows the current line number at the bottom-right
                               " of the screen.
set wildmenu                   " Great command-line completion, use `<Tab>` to move
                               " around and `<CR>` to validate.
set tabstop=2                  " Set tab character to show as 2 spaces
set softtabstop=2              " Set tab to input 2 spaces
set list                       " Enable visibility of spaces and tab characters"
set listchars=multispace:\ \ ┊ " Set indentation to show a modified pipe"
set expandtab                  " Change tabs to spaces"
set number                     " Enable line numbers
set cursorline                 " Show a line where the cursor is
set lazyredraw                 " Don't redraw the screen all the damn time
set showmatch                  " Show matching brackets [ ]

" Code folding options
set foldenable                 " Eable folding of code blocks
set foldlevelstart=10          " Expand most folds
set foldmethod=indent

" Set <space> to open/close folds
nnoremap <space> za

" :W sudo saves the file
" (useful for handling the permission-denied error)
command! W execute 'w !sudo tee % > /dev/null' <bar> edit!

" Load Dracula-Pro Theme
packadd! dracula_pro
syntax enable
let g:dracula_colorterm = 0
colorscheme dracula_pro

" Allow crosshair cursor highlighting.
hi CursorLine   cterm=NONE ctermbg=0
hi CursorColumn cterm=NONE ctermbg=0
nnoremap <Leader>c :set cursorline! cursorcolumn!<CR>

" set \<space> to clear search
nnoremap <leader><space> :nohlsearch<CR>

" make 'j' and 'k' smarter about wrapping lines
nnoremap j gj
nnoremap k gk

" disable netrw
let g:loaded_netrw       = 0
let g:loaded_netrwPlugin = 0